### PR TITLE
Release 3.2.1 D3.V5 Fix

### PR DESCRIPTION
**Pull request by msusol**
* Fix missing labels and other D3.V3 to D3.V5 issues.
* Revert the indexing changes i.e. (startIndex - 1).
* Removed some unused GLOBALs.

### CODE REVIEW

**Comment by msusol** [comment]
@bmabey Are you available to merge this PULL request with the D3.V5 fix?

**Comment by bmabey** [comment]
Were the `startIndex` changes causing the problem? I thought they had properly defaulted it so it would not have changed anything.

**Comment by bmabey** [comment]
Regardless, thank you for doing this and making such a complete PR and release! I've merged it in and released it.

**Comment by msusol** [comment]
I don't understand why the start Index change was made. I reverted all of those changes, and didn't see the need for the change. It wasn't what caused the main issue though. There was a line of javascript not related to D3.V5 upgrade that stopped working i guess. It has been there for awhile. I compared to original D3.V3 version. There was also a missing D3.V5 function change (sqr root).

You're welcome!

**Comment by msusol** [comment]
@bmabey How do you update the "cdn" files?

https://cdn.jsdelivr.net/gh/bmabey/pyLDAvis/pyLDAvis/js/ldavis.v3.0.0.js
does not match
https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/js/ldavis.v3.0.0.js

**Comment by ed9w2in6** [comment]
@msusol No, those changes are necessary for custom `start_index` to function.

I have created a new issue (https://github.com/bmabey/pyLDAvis/issues/265) for this.

**Comment by ed9w2in6** [comment]
@msusol 
https://github.com/bmabey/pyLDAvis/pull/266 should revert only the changes that involves `startIndex`.

**Pull request merged**
