### PR TITLE
Changes setup.py to reference requirements.txt

### PR DESCRIPTION
**Pull request by cemoody**
Instead of having two places with separate lists of libraries, now there's one. 

I also fix an import error with the newest skbio

### CODE REVIEW

**Comment by bmabey** [comment]
Great, thank you for for this!

**Comment by piskvorky** [comment]
Thanks Chris, we ran into exactly the same issues (JSON serialization of NumPy types, skbio renames).

I wanted to submit a fix but I see you've already done all the hard work :+1: 

Thank you Ben for your responsive maintenance and releases!

**Comment by piskvorky** [comment]
Actually, the package now fails to install from PyPI:

```bash
$ pip install -U pyLDAvis
Collecting pyLDAvis
  Using cached pyLDAvis-1.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-B4YGsH/pyLDAvis/setup.py", line 47, in <module>
        with open('requirements.txt') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
```

It seems the latest release is broken. Or am I doing something wrong? Does it work for you? @cemoody @bmabey

**Comment by bmabey** [comment]
@piskvorky Ah, thanks for the report. I've cut a new release (1.4.1) with the `requirements.txt` file actually in the MANIFEST. I was able to install it in a new conda env. Please let me know how it works for you.

**Comment by piskvorky** [comment]
I confirm this new version installs and works.

Thanks again for such responsive maintenance :)

**Pull request merged**
