### PR TITLE
support for manual topic tagging

### PR DESCRIPTION
**Pull request by Mageswaran1989**
Enhancement for https://github.com/bmabey/pyLDAvis/issues/89

Please review.

Features:
- Init Button: Initial the topics with default valuues. eg: topic-0
- Load Button: Loads a json file with array of strings of size K
- Save Button: Downloads the current topic modelling (array of string of size K) to a json file.

### CODE REVIEW

**Comment by Mageswaran1989** [comment]
screenshot from 2017-04-14 18-26-22

**Comment by Mageswaran1989** [comment]
@bmabey Please review

**Comment by bmabey** [comment]
Where is the `FileSave` module/file loaded from the main JS?

**Comment by Mageswaran1989** [comment]
do you mean to add in https://github.com/bmabey/pyLDAvis/blob/master/pyLDAvis/_display.py ?

**Comment by Mageswaran1989** [comment]
@bmabey review the changes based on my assumption, if the changes are correct need your help to modify the url.py

**Comment by Mageswaran1989** [comment]
@bmabey 
I am new to JS need your insight in making further changes. 
Would  you please take some time and help me out with closing this PR?

**Comment by Mageswaran1989** [comment]
@bmabey could you spend some time in helping me to make further changes?

**Comment by Mageswaran1989** [comment]
Scala port to support Apache Spark LDA Model is available @ https://github.com/iaja/scalaLDAvis/tree/master

**Comment by rchaturvedulla** [comment]
Hi, I am trying to use the topic name tags, can you please let me know if the latest release of pyldavis or the github version has this inbuilt currently.

**Comment by nmakarun** [comment]
Was this issue resolved, please help in identifying how to change the topic names, I can change in HTML and it refelcts. But its not interactive, since the VIS is loaded based on d3 and js files.
https://cdn.rawgit.com/bmabey/pyLDAvis/files/ldavis.v1.0.0.js. 

Please point me in right direction.

**Comment by msusol** [comment]
Obsoleting.. please reevaluate the issue with v3.3.0 and create a new issue/PR for testing.

**Pull request closed without merging**
